### ISSUE TITLE
Écrire et publier la documentation sur le langage Touist

### ISSUE THREAD

**Issue by maelvalais** [olzd/touist#10]
PDF + textuel dans le README.me

**Comment by olzd** [comment]
J'ai ajouté la liste des mots-clés (utile pour la coloration syntaxique) et un tableau récapitulatif des différents opérateurs/fonctions. La grammaire à venir...

**Comment by maelvalais** [comment]
Merci pour ton travail :) Voilà pour ceux qui en ont besoin : https://drive.google.com/open?id=0B5mz8k-t6PT0N1hscXVpTWt4SUE&authuser=0
![capture d ecran 2015-03-13 a 17 21 46](https://cloud.githubusercontent.com/assets/2195781/6642523/7fede6c4-c9a5-11e4-9a31-af39fe9e0466.png)

**Comment by maelvalais** [comment]
Bon ben je suppose qu'on peut dire que pour le moment, la tâche est terminée !

**Comment by maelvalais** [comment]
@olzd Je n'ai pas retrouvé comment écrire un commentaire en langage touistl, quelle est la syntaxe ? Merci :)
