### ISSUE TITLE
"a and b or c" ou "(a and b) or c" ne prend pas en compte le litéral "b" dans la traduction

### ISSUE THREAD

**Issue by aheba** [olzd/touist#11]
Il faudrait corriger l'erreur rencontrée avec ce type d'entrée Touistl :
~~~
begin formula
(a and b) or (c and not t)
end formula
~~~
Le résultat DIMACS (semble faux car il y a 3 variables au lieu de 4) :
~~~
c CNF format file
p cnf 3 2
2 3 0
2 -1 0
~~~
Et Table.out :
~~~
a 2
t 1
c 3
~~~
Le résultat devrait être, pour `table.out` :
~~~
a  indx
b indx1
t indx2
c indx2
~~~
Et le fichier DIMACS devrait être un truc comme ça (les propositions sont normalement des entiers) :
~~~
a or c
a or not t
b or c
b or not t
~~~

**Comment by olzd** [comment]
I didn't find the source of this bug but I can't reproduce it anymore. I guess I'll just close the issue.

**Comment by maelvalais** [comment]
Je réouvre le ticket : 
- Si on fait `(a and b or c)`, seuls les litéraux a et c sont "pris en compte" : 

![capture d ecran 2015-03-13 a 10 06 28](https://cloud.githubusercontent.com/assets/2195781/6635654/ad6a6da8-c968-11e4-99b1-dd22b4258a45.png) ![capture d ecran 2015-03-13 a 10 05 49](https://cloud.githubusercontent.com/assets/2195781/6635639/96664e6a-c968-11e4-9b11-04690e8ecc82.png)

- Si on fait `((a and b) or c)`, idem, seuls a et c sont pris en compte :

![capture d ecran 2015-03-13 a 10 06 44](https://cloud.githubusercontent.com/assets/2195781/6635672/d10b04ca-c968-11e4-91aa-b1dd9361cd2e.png) ![capture d ecran 2015-03-13 a 10 05 49](https://cloud.githubusercontent.com/assets/2195781/6635674/d4201538-c968-11e4-901f-f444012a4705.png)

- Par contre si on fait `(a and (b or c))`, là ça marche : 

![capture d ecran 2015-03-13 a 10 10 19](https://cloud.githubusercontent.com/assets/2195781/6635718/4832b19c-c969-11e4-9e1d-1b41f586ea59.png) ![capture d ecran 2015-03-13 a 10 10 34](https://cloud.githubusercontent.com/assets/2195781/6635721/4be70784-c969-11e4-9a03-360a6a503590.png)

**Comment by olzd** [comment]
Les 3 formules marchent chez moi. Je comprends pas. T'as bien récupéré la dernière version du traducteur?

**Comment by maelvalais** [comment]
Je reteste ^^
