### ISSUE TITLE
Implementer la traduction .touitl vers SMT-LIB2 

### ISSUE THREAD

**Issue by maelvalais** [olzd/touist#16]

**Comment by maelvalais** [comment]
@olzd Où en es tu ?

**Comment by olzd** [comment]
Je finis ce weekend normalement. Donc ça devrait me laisser une semaine pour tout bien mettre en place et vérifier que tout marche, corriger les bugs...

**Comment by olzd** [comment]
Bon j'ai push. J'ai testé sur de petits exemples et ça a l'air de marcher. Le fichier généré est dégueulasse par contre niveau lisibilité ^^

**Comment by maelvalais** [comment]
J'ai aucune idée de ce que donne ce fameux SMT en `.touistl`… Tu aurais pas un petit exemple ? :)

**Comment by olzd** [comment]
```ruby
begin formula
  bigand $i in [1..5]:
    (a($i) > 0) and b($i)
  end
end formula
```
Pour l'appel: `./touistc.native -smt2 qf_nia file.touistl` par exemple.
