### ISSUE TITLE
Le set "ensemble vide" ($Del(B) = []) ne fait pas partie du langage  Touistl

### ISSUE THREAD

**Issue by maelvalais** [olzd/touist#24]
Encore un petit truc qui manque pour arriver à traduire l'exemple de F. Maris. Dans l'exemple suivant :
~~~
begin sets
  $Del(B) = []
end sets

begin formula
bigand $f in $I: $f(0) end
bigand $f in ($F minus $I): not $f(0) end
bigand $f in $G: $f($length) end
end formula
~~~
il semble impossible de donner à une variable de set l'ensemble vide (`$Del(B) = []`). Peut-être que je n'ai pas réussi à trouver la bonne façon de traduire ça dans le langage touistl.

**Comment by olzd** [comment]
Le problème c'est que les sets sont typés :  un set peut contenir soit des entiers, soit des flottants, soit des termes. Quand on déclare un set vide comme tu l'as fait on n'a pas d'information sur son type donc on ne peut pas vraiment prendre de décisions.

**Comment by maelvalais** [comment]
Ah, effectivement, je me suis fait cette remarque mais j'étais pas sûr... Du coup, comment traduire qu'un set est vide ? Faut-il traduire ça différemment ?

**Comment by olzd** [comment]
Du coup je sais pas comment faire...

**Comment by olzd** [comment]
Bon, j'ai une solution qui a l'air de marcher. J'ai ajouté au module set générique `GenSet` un contructeur `Empty`. Plus qu'à intégrer tout ça et modifier l'évaluation des expressions pour en tenir compte.

**Comment by maelvalais** [comment]
Bien joué :p J'espère que les modifications des évaluations seront pas trop chronophages :)

**Comment by olzd** [comment]
Les sets vides devraient maintenant être supportés.
