### ISSUE TITLE
La hiérarchie du projet devrait être plus claire pour la procédure de "distribution" du logiciel

### ISSUE THREAD

**Issue by maelvalais** [olzd/touist#25]
Pour l'instant, `ui` contient les sources du projet java et `compiler` les sources du projet ocaml. Donc on devrait remettre ça à plat : 
~~~
.
  touist-gui
    bin (pas sur le dépôt)
    build (pas sur le dépôt)
    libs
      rsyntaxtextarea-2.5.6.jar
      sat4j-sat.jar (pas pour la version définitive)
      Minisat.class
    src
      entity
      translation
      gui
      touist
      solution
  touist-compiler
    build (pas sur le dépôt)
    bin
    src
      ast.ml
      eval.ml
      lexer.mll
      parser.mly
      touistc.ml
      cnf.ml
      dimacs.ml
    
~~~

**Comment by maelvalais** [comment]
D'ailleurs, pour la distribution, il faudrait un truc du genre 
~~~
./touist-win32.zip
    touist.jar
    libs
        minisat.jar (qui contient sat4j-sat.jar)
        rsyntaxtextarea-2.5.6.jar
        touistc.native (version win32)
~~~
Idem pour MacOSX et linux.

**Comment by maelvalais** [comment]
Voilà une branche avec les propositions de clarification de la hiérarchie (un gros refactor quoi). J'ai essayé de faire des commits "atomiques" (7ab1f91)
https://github.com/olzd/touist/tree/fix-project-hierarchy-%2325

**Comment by aheba** [comment]
Bonjour à tous,
c'est une bonne hiérarchie sauf qu'il faudra la completer:
je pense que nous avons négligé une grande partie dans notre plateforme "La gestion des fichiers généré", il me semble qu'on doit séparé:
  1/ la génération de code "touistL"
 2/ la génération du code dimacs/CNF/Map-model/SMT-LIB
ce que je propose est de créer deux dossier supplémentaire: 
TouistL "contenant tout les fichiers que l'utilisateur a executer, en prenant compte la date d'execution" et un dossier Gen-Code "contenant les fichiers généré par le traducteur"

d'autre part je pense que je finirai le programme en console ce week end. il faut penser comment le mettre en place!!!.

**Comment by maelvalais** [comment]
Merci pour tes remarques !

En fait, je parlais de la hiérarchie du projet, pas celle du programme "distribué".

Ce que tu proposes concerne le programme/dossier/zip distribué. En gros, tu parles du dossier `./dist` qui est généré pour les releases.

Note : en fait le dossier `./dist` devra être renommé `./touist-osx64` ou `./touist-windows` en fonction du `touisc` qu'on met dedans.

~~~
./dist
	touist.jar
	external/touisc
	external/minisat.jar
	touistl/le_fichier_touistl
	gen-code/out-28_03_2015-11_30.cnf
	gen-code/out-28_03_2015-11_30.table
	gen-code/out-28_03_2015-15_30.cnf
	gen-code/out-28_03_2015-15_30.table
~~~

Un truc comme ça ?

**Comment by aheba** [comment]
oui effectivement, c'est bien de la distribution que je parle. je tiens à préciser qu'il y'aura du code derriere qui sera modifier pour une tel distribution.

**Comment by maelvalais** [comment]
J'ai ajouté un fichier `build.xml` utilisé par `ant` pour simplifier la mise dans un `touist.jar`.
La commande est `ant build-jar`.

**Comment by maelvalais** [comment]
![capture d ecran 2015-03-29 a 18 56 18](https://cloud.githubusercontent.com/assets/2195781/6886679/3d35ac1a-d646-11e4-8dfe-c7cfc7af4cee.png)

**Comment by maelvalais** [comment]
Problème réglé, je ferme l'issue
