### ISSUE TITLE
Depuis la mise en place de "champ unique", la BaseDeClause ne semble pas être remplie quand on appuie sur "Test"

### ISSUE THREAD

**Issue by maelvalais** [olzd/touist#31]

**Comment by maelvalais** [comment]
En fait, je crois que c'est pas les fonctions de Alexis qui ne fonctionnent pas : quand je débug, je regarde le contenu de l'instance BaseDeClause (avec `getFrame().getClause()`)... Et c'est vide. Bizarre...

**Comment by Aleksandair** [comment]
Effectivement j'avais oublié ces 2 lignes quand j'ai adapté la nouvelle interfaces.

**Comment by maelvalais** [comment]
Super ! Maintenant ça marche parfaitement ! Je ferme l'issue du coup.
