### ISSUE TITLE
Implémenter les "champs" sélectionnables lors de l'ajout de "snippets"

### ISSUE THREAD

**Issue by maelvalais** [olzd/touist#36]

**Comment by cup2of2tea** [comment]
Concernant les champs séléctionnables, doit-on pouvoir switcher entre des champs déjà modifiés ou pas?
Personnellement je pense que non, vu que l'utilisateur aurait du mal à comprendre pourquoi les champs séléctionnables des snippets modifiés peuvent être selectionnés, mais pas les champs des parties de formules créés manuellement (et si l'on veut détecter les champs créés manuellement, on est obligé de passer par un parsing "live" coûteux).

Je commencerai cette tâche après 19h30 (http://codeforces.com/contests/529, si quelqu'un est tenté).

**Comment by maelvalais** [comment]
@cup2of2tea Bonne initiative la VK Cup, j'aurais jamais pensé à participer à ce genre d'évènement ! 

Pour les champs déjà modifiés, c'est une bonne question... Dans les deux éditeurs que je connais (eclipse et vim) qui proposent ce genre de feature, quand un champ a été modifié, le surlignage de "champ" disparait et ça devient du texte classique. Du coup, je suppose qu'on va faire un truc pareil...

**Comment by maelvalais** [comment]
Par exemple quand j'utilise le plugin `snipmate` sous `vim`, en tapant `main`+ctrl+space j'obtiens un *snippet*, c'est à dire un bout de code que j'ai prédéfini. Ainsi sur le premier `placeholder` (la dénomination du "champ" dans ce plugin) ça donne ça :

![capture d ecran 2015-03-21 a 20 26 47](https://cloud.githubusercontent.com/assets/2195781/6766503/dcf200a8-d008-11e4-97c2-02cdf5d3f3c3.png)
Du coup le placeholder en cours est affiché "présélectionné". Quand je tape du texte, ça le remplace. Quand je fais "tab", ça passe au placeholder suivant :

![capture d ecran 2015-03-21 a 20 26 57](https://cloud.githubusercontent.com/assets/2195781/6766508/330acb64-d009-11e4-98a7-e9fc832dc408.png)

Et quand je refais encore "tab", ça passe à un placeholder fictif qui est en fait la place du curseur/caret qu'on veut quand on a terminé les placeholder

![capture d ecran 2015-03-21 a 20 27 03](https://cloud.githubusercontent.com/assets/2195781/6766521/8f228dec-d009-11e4-90cc-0be581ee3c92.png)

**Comment by cup2of2tea** [comment]
Ca fonctionne. 
Par contre, j'ai choisi d'ignorer certains champs de formules, certaines semblant être présentes uniquement pour une démonstration, car très spécifiques ("bigand $i in $a: A($i) and B($i) end" sera surement remplacé par quelque chose dans ce style pour la version finale: "bigand $i in $a: EXP end". Donc dans cette formule, seuls $i et $a avant le ":" sont considérés comme snipets).

**Comment by maelvalais** [comment]
Comment l'intégration au reste de l'interface va se faire ? @Aleksandair doit-il le faire ? Désolé, j'ai pas suivi ça :/

**Comment by cup2of2tea** [comment]
Non c'est déjà fait. C'est la classe éditeur qui gère les raccourcis, donc les snippets marchent déjà depuis le programme principal.

**Comment by maelvalais** [comment]
Ah, j'oubliais de préciser que sous MacOSX, le raccourci `ctrl+left`/`ctrl+right` est déjà pris (par défaut) par "aller au bureau à droite" et "aller au bureau de gauche". Avec `tab` ça serait super, c'est possible ?

@cup2of2tea Je n'arrive pas à faire fonctionner tout ça, comment ça marche ? :)

**Comment by cup2of2tea** [comment]
Sauf que tab est utile pour l'indentation.
Donc il faudrait trouver un raccourci satisfaisant tout le monde.

Pour le faire fonctionner, il suffit d'utiliser le menu de gauche pour insérer une ou plusieurs portions de formules, et d'utiliser le raccourci pour naviguer entre les différents champs modifiables.

**Comment by maelvalais** [comment]
Ah ok. J'ai désactivé le `ctrl+left/right` sur ma machine et effectivement, ça marche nickel !

Deux petites questions subsistent :
- Si l'utilisateur ne voit pas (avant d'avoir fait `ctrl+right`) qu'on doit/peut modifier les placeholders, ça ne dérange pas ?
- L'utilisateur n'est pas obligé de modifier les placeholders ?
- Il ne faudrait pas que tous les placeholders soient visibles avec par exemple un surlignage fluo ou un truc du genre ?

Quoi qu'il en soit, c'est du super bon boulot !!!

**Comment by cup2of2tea** [comment]
Oui on peut faire ça. Je vais rajouter un surlignage, ce soir surement.
"L'utilisateur n'est pas obligé de modifier les placeholders ?" Si la question est "est-ce qu'il peut compiler sans les modifier", oui.
Pour la première question, avec le surlignage ce sera plus explicite, mais sinon, il verra la liste des raccourcis et fonctionnalités dans le manuel.
On peut aussi rajouter un bouton d'aide dans la barre de menu, comme le font la plupart des programmes. Ça prendra juste un peu de temps à compléter.

**Comment by maelvalais** [comment]
On va dire que c'est bon :)
