### ISSUE TITLE
Besoin d'aide pour traduire le problème de planification de M. Maris en touistl

### ISSUE THREAD

**Issue by maelvalais** [olzd/touist#39]
Voilà : mon objectif est de traduire tout ce problème. Du coup, j'espère que les sets vides de l'issue #24 est bientôt terminée, car pour le moment je bloque sur `$Del(B) = []`.
@olzd Je te mets au défi de faire fonctionner tout ça avec moi :p 

**ATTENTION : ce code ne respecte pas la syntaxe. Un code respectant la syntaxe est donné plus bas.**
~~~
begin sets
  $length = 10
  $F = [a,b,c,d]
  $O = [A,B]
  $I = [a,c]
  $G = [a,d]
  $Prec(A) = [a]
  $Add(A) = [b]
  $Del(A) = [a]
  $Prec(B) = [b,c]
  $Add(B) = [a,d]
  $Del(B) = []
end sets

begin formula

bigand $f in $I: $f(0) end
bigand $f in diff($F,$I): not $f(0) end
bigand $f in $G: $f($length) end
bigand $i in [1..$length]:
  (bigand $a in $O:
    ($a($i) =>
      (
        (bigand $f in Prec($a): $f($i-1) end)
        and
        (bigand $f in Add($a): $f($i) end)
      )
    )
    and
    (bigand $f in Del($a): (not $f))
  )
end
bigand $i in [1..$length]:
  bigand $f in $F:
    ((not $f($i-1)) and $f($i))
    => (bigor $a in $O such $f in Del($a): $a($i) end)
  end
end
bigand $i in [1..$length]:
  bigand $f in $F:
    (not $f($i-1) and not $f($i))
    => (bigor $a in $O such $f in Add($a): $a($i) end)
  end
end
bigand $i in [1..$length]:
  bigand $a1 in $O:
    bigand $f in Prec($a1):
      bigand $a2 in $O such ($a1 <> $a2) and ($f in Del($a2)):
        (not $a1($i) or not $a2($i))
      end
    end
  end
end
end formula
~~~

**Comment by maelvalais** [comment]
@cup2of2tea Si tu as du temps, tu peux tenter de debug cet exemple de problème en utilisant `touistc.native` (j'ai pas pu compiler la version linux par contre, mais tu peux le compiler facilement).

**Comment by maelvalais** [comment]
Je poste ici le message de @cup2of2tea qui a remonté un souci avec la grammaire : 

1. Impossible de faire `$A = [3*3,int(42)]`, alors que `$A = [3*3..int(42)]` accepté (seuls des atomes sont acceptés pour la séparation par virgules. `num-expr` à la place de `nb` et `bool-expr` à la place de `bool`?)
- `$B = [(42)]` refusé, mais `$B = [42]` accepté (même principe)
- `$a.($i) => $a.($i)` refusé, car `$a.($i)` n’est pas une `clause-expr` (d’ailleurs, on garde cette syntaxe? ou bien c’est `$a($i)` ?)

**Comment by olzd** [comment]
Pour le point 1, bien vu j'ai complètement zappé la possibilité qu'on puisse vouloir rentrer des expressions (numérique et booléenne). Le point 2 découle du point 1.

Pour le point 3, c'est plus compliqué. Il y a un opérateur `.` sur les sets donc `$a.($i)` est viable et différent de `$a($i)`. Chez moi `$a.($i)` doit retourner l'élément `$i` s'il est dans le set `$a`.  
Je suspecte que le comportement voulu aurait été de retourner l'élément du set `$a` d'indice `$i` mais le problème c'est que l'ordre des éléments d'un set n'est pas conservé (par rapport à l'ordre d'insertion)...

**Comment by olzd** [comment]
Les points 1 & 2 ne devraient plus poser de problèmes.

**Comment by maelvalais** [comment]
@olzd du coup j'ai pu détecter mes erreurs lorsque j'ai "traduit" en touistl :
- J'avais écrit `($F minus $I)` au lieu de `diff($F,$I)` (d'ailleurs, l'écriture infixe était pratique :p)
Mais `diff($F,$I)` ne passe pas (erreur sur la parenthèse ouvrante). J'ai peut-être fait une erreur de typage ou je ne sais quoi...

Note : j'ai utilisé `touistl-grammar.pdf` sur le drive

**Comment by olzd** [comment]
Je pense que c'est parce que la grammaire est ambigüe :  `$F` et `$I` désignent des variables mais le parser ne peut pas dire si elles correspondent à un `int`, un `float`, un `set`... Or `diff` attend 2 `set`.  
Bref, j'ai du boulot.

**Comment by cup2of2tea** [comment]
A tout hasard, y'aurait pas un parser générator Ocaml non déterministe avec une syntaxe proche pour que la conversion se fasse "facilement"? Je sais pas si c'est plus simple que de redéfinir la grammaire...

**Comment by olzd** [comment]
J'ai ajouté l'exemple corrigé (pas grand chose) dans le répertoire `test/` de la branche `translator-new-ast-parser`. L'exemple marche dans le sens où on arrive bien à générer un fichier au format DIMACS. Après faut voir si la génération est correcte...

**Comment by maelvalais** [comment]
Ce problème semble insatisfiable… à moins que la traduction ne soit pas bonne… 
![capture d ecran 2015-04-20 a 23 55 41](https://cloud.githubusercontent.com/assets/2195781/7241375/d73568fe-e7b8-11e4-9ca5-8f0704f6d263.png)

**Comment by maelvalais** [comment]
~~~
c CNF format file
p cnf 65 156
64 0
61 0
-63 0
-60 0
9 0
2 0
-62 64 0
-62 57 0
-65 0
-59 63 0
-59 61 0
-59 58 0
-59 54 0
-56 58 0
-56 51 0
-65 0
-53 57 0
-53 55 0
-53 52 0
-53 48 0
-50 52 0
-50 45 0
-65 0
-47 51 0
-47 49 0
-47 46 0
-47 42 0
-44 46 0
-44 39 0
-65 0
-41 45 0
-41 43 0
-41 40 0
-41 36 0
-38 40 0
-38 33 0
-65 0
-35 39 0
-35 37 0
-35 34 0
-35 30 0
-32 34 0
-32 27 0
-65 0
-29 33 0
-29 31 0
-29 28 0
-29 24 0
-26 28 0
-26 21 0
-65 0
-23 27 0
-23 25 0
-23 22 0
-23 18 0
-20 22 0
-20 15 0
-65 0
-17 21 0
-17 19 0
-17 16 0
-17 12 0
-14 16 0
-14 8 0
-65 0
-11 15 0
-11 13 0
-11 10 0
-11 3 0
-6 10 0
-6 7 0
-65 0
-1 8 0
-1 5 0
-1 9 0
-1 2 0
64 -58 62 0
63 -57 0
61 -55 0
60 -54 0
58 -52 56 0
57 -51 0
55 -49 0
54 -48 0
52 -46 50 0
51 -45 0
49 -43 0
48 -42 0
46 -40 44 0
45 -39 0
43 -37 0
42 -36 0
40 -34 38 0
39 -33 0
37 -31 0
36 -30 0
34 -28 32 0
33 -27 0
31 -25 0
30 -24 0
28 -22 26 0
27 -21 0
25 -19 0
24 -18 0
22 -16 20 0
21 -15 0
19 -13 0
18 -12 0
16 -10 14 0
15 -8 0
13 -5 0
12 -3 0
10 -9 6 0
8 -7 0
5 -4 0
3 -2 0
64 58 59 0
63 57 62 0
61 55 0
60 54 59 0
58 52 53 0
57 51 56 0
55 49 0
54 48 53 0
52 46 47 0
51 45 50 0
49 43 0
48 42 47 0
46 40 41 0
45 39 44 0
43 37 0
42 36 41 0
40 34 35 0
39 33 38 0
37 31 0
36 30 35 0
34 28 29 0
33 27 32 0
31 25 0
30 24 29 0
28 22 23 0
27 21 26 0
25 19 0
24 18 23 0
22 16 17 0
21 15 20 0
19 13 0
18 12 17 0
16 10 11 0
15 8 14 0
13 5 0
12 3 11 0
10 9 1 0
8 7 6 0
5 4 0
3 2 1 0
~~~

Table de correspondance : 
~~~
a(3) 46
a 65
A(4) 44
B(5) 35
A(7) 26
B(3) 47
c(10) 4
d(9) 3
d(8) 12
a(0) 64
c(4) 37
A(6) 32
b(10) 7
b(0) 63
B(4) 41
c(5) 31
a(6) 28
B(10) 1
a(10) 9
b(3) 45
b(1) 57
B(2) 53
a(1) 58
d(1) 54
B(9) 11
B(6) 29
b(6) 27
c(0) 61
A(3) 50
c(2) 49
c(3) 43
d(10) 2
d(4) 36
d(6) 24
A(8) 20
A(2) 56
b(2) 51
d(2) 48
a(5) 34
d(3) 42
b(8) 15
a(9) 10
d(5) 30
c(6) 25
a(8) 16
c(9) 5
A(10) 6
a(4) 40
d(0) 60
B(7) 23
A(5) 38
B(1) 59
B(8) 17
a(2) 52
a(7) 22
c(1) 55
A(9) 14
b(5) 33
A(1) 62
c(8) 13
b(4) 39
b(9) 8
b(7) 21
c(7) 19
d(7) 18 
~~~

**Comment by maelvalais** [comment]
Corrections apportées par M. Maris : 
- ligne 11: remplacer `(not $f)` →  `(not $f($i))`
- ligne 16: remplacer `((not $f($i-1)) and $f($i))` → `($f($i-1) and not $f($i))`
- ligne 22: remplacer `(not $f($i-1) and not $f($i))` →  `(not $f($i-1) and $f($i))`

Du ça donne : 
~~~ruby
begin sets
$length  = 10
$F       = [a,b,c,d]
$O       = [A,B]
$I       = [a,c]
$G       = [a,d]
$Prec(A) = [a]
$Add(A)  = [b]
$Del(A)  = [a]
$Prec(B) = [b,c]
$Add(B)  = [a,d]
$Del(B)  = []

end sets
begin formula
bigand $f in $I: $f(0) end
bigand $f in diff($F,$I): not $f(0) end
bigand $f in $G: $f($length) end
bigand $i in [1..$length]:
  bigand $a in $O:
    ($a($i) =>
      ((bigand $f in $Prec($a): $f($i-1) end)
        and
        (bigand $f in $Add($a): $f($i) end)))
    and
    (bigand $f in $Del($a): (not $f($i)) end)
  end
end
bigand $i in [1..$length]:
  bigand $f in $F:
    (($f($i-1)) and $f($i))
    => (bigor $a in $O when $f in $Del($a): $a($i) end)
  end
end
bigand $i in [1..$length]:
  bigand $f in $F:
    (not $f($i-1) and $f($i))
	=> (bigor $a in $O when $f in $Add($a): $a($i) end)
  end
end
bigand $i in [1..$length]:
  bigand $a1 in $O:
    bigand $f in $Prec($a1):
      bigand $a2 in $O when ($a1 != $a2) and ($f in $Del($a2)):
        (not $a1($i) or not $a2($i))
      end
    end
  end
end
end formula
~~~

**Comment by maelvalais** [comment]
Je ne comprends pas cette erreur : 
![capture d ecran 2015-05-01 a 23 57 09](https://cloud.githubusercontent.com/assets/2195781/7438002/d2d3f7dc-f05d-11e4-8b27-28736199612d.png)

**Comment by olzd** [comment]
Ca veut dire que le résultat est toujours vrai et qu'il n'y a pas besoin de lancer de solveur.

**Comment by maelvalais** [comment]
Merci :)

Le sam. 2 mai 2015 03:03, Olivier Lezaud <notifications@github.com> a
écrit :

**Comment by olzd** [comment]
Par contre c'est pas dit que ce soit vraiment le cas...
