### ISSUE TITLE
Problème avec les A($i) dans un bigand

### ISSUE THREAD

**Issue by maelvalais** [olzd/touist#48]
~~~
begin formula
    bigand $i in [1..3] do
        A($i)
    end
end formula
~~~
Bug sur la parenthèse fermante de ` A($i)`

**Comment by olzd** [comment]
Nouvelle branche `translator-new-ast-parser` qui devrait régler ça.

**Comment by maelvalais** [comment]
Tu carbures là :p

**Comment by olzd** [comment]
Corrigé dans la branche `translator-new-ast-parser`.
