### ISSUE TITLE
Permettre à l'utilisateur de sauvegarder un modèle depuis la fenêtre des résultats

### ISSUE THREAD

**Issue by maelvalais** [olzd/touist#52]

**Comment by cup2of2tea** [comment]
La forme sous laquelle le modèle est sauvegardée est libre? 
Est-ce qu'il faut que le fichier produit soit au format dimacs, ou bien je peux simplement afficher le modèle sous la forme présentée par l'ancienne fenêtre de résultat ("machin valuted to truc" etc...).
On pourrait même ouvrir un petit dialogue avec une liste d'options (sauvegarder sous format pdf (donc "machin valuted..."), sous dimacs, sous texte...).

**Comment by maelvalais** [comment]
A priori c'est un format libre, à toi de choisir ; si possible pas du dimacs, les gens voulant ce format utiliseront directement traducteur+solveur. M'enfin pas sûr, faudrait demander précision à F Maris et O Gasquet
