### ISSUE TITLE
Permettre à l'utilisateur de filtrer les littéraux grâce à un champ "regex" dans la fenêtre des résultats

### ISSUE THREAD

**Issue by maelvalais** [olzd/touist#53]

**Comment by cup2of2tea** [comment]
Transformation en tableau réalisée. 
Tri implémenté.
To do: filtrage.

**Comment by cup2of2tea** [comment]
Ca ressemble à ça pour l'instant.
(0,0): filtrage par regex + filtrage pour literaux évalués à True
(0,1): tri et filtrage par défaut (le tri par value est une coincidence, l'ordre est défini par l'ordre donné par le solver)
(1,0): tri par nom, filtrage par défaut
(1,1): tri par valeur, filtrage par défaut.
To do: utiliser les fichiers de langues pour les noms de colonnes, valeurs et checkbox.

Comme d'hab: suggestions? 

![demotrifiltrage](https://cloud.githubusercontent.com/assets/2098612/7048178/9b417de8-de11-11e4-9200-2eec34142d9e.jpg)
