### ISSUE TITLE
Exception anormale récupérée dans le cas où il n'existe pas de modèle

### ISSUE THREAD

**Issue by cup2of2tea** [olzd/touist#54]
`a and not b`  fonctionne bien (a valuted to true and b valuted to false)
mais
`a and not a` déclenche une exception de type "java.lang.NumberFormatException"
(Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: "Incorrect")

**Comment by cup2of2tea** [comment]
Il semblerait que le problème vient de SolverTestSAT4J. Dans le cas où il n'existe pas de modèle, le solver retourne une chaine de caractère "Incorrect", qu'on essaie de parser en Integer.

**Comment by maelvalais** [comment]
Je regarde

**Comment by maelvalais** [comment]
Dans minicar.java : 
~~~java
catch (ParseFormatException e) {
            System.out.println("Incorrect Dimacs Content");
            System.exit(3);
 }
~~~
C'est ce "Incorrect" qui est attrapé. Mais vu qu'il y a un exit(3) et que donc le code d'erreur devrait empêcher le parsing, il y a un souci...

**Comment by maelvalais** [comment]
Ok, en fait ça vient à priori du traducteur : le traducteur donne
~~~
c CNF format file
p cnf 0 1
 0
~~~

**Comment by maelvalais** [comment]
Je viens de faire des tests, il y a aussi un souci avec `launch()` car `minicar.jar` renvoie `exit(3)` un peu trop tard, et donc `launch()` n'a pas encore eu le temps de voir que le programme a quitté.

**Comment by olzd** [comment]
Je regarderai. A priori c'est dû au fait que `a and not a` est toujours faux donc ça sert à rien de générer un fichier dimacs puisqu'on connaît le résultat. Le mieux serait de retourner une erreur pour l'indiquer.

**Comment by olzd** [comment]
Problème corrigé (dans la branche `translator-new-ast-parser`).
