### ISSUE TITLE
Lignes séparatrices dans Résultats

### ISSUE THREAD

**Issue by maelvalais** [olzd/touist#64]
OG : Il faudrait des lignes séparatrices dans la fenêtre d'affichage des modèles sinon on risque de se tromper de ligne...

**Comment by cup2of2tea** [comment]
Quelqu'un peut vérifier sous mac?
Sous windows on avait déjà les lignes séparatrices.

**Comment by cup2of2tea** [comment]
J'ai aussi alterné la couleur des lignes. Si quelqu'un a une meilleure idée, j'ai pris la première couleur acceptable.

**Comment by maelvalais** [comment]
Voilà le résultat sous mac os : 
![capture d ecran 2015-04-20 a 09 37 53](https://cloud.githubusercontent.com/assets/2195781/7227520/92e60b48-e751-11e4-8ceb-5e0dc2b99279.png)
Par contre quand on sélectionne une valeur, on ne **peut plus la désélectionner** et le texte devient de couleur blanche (et **donc disparait**).

**Comment by cup2of2tea** [comment]
Ce problème était déjà rencontré avant la modification?

**Comment by maelvalais** [comment]
Aucune idée, je n'avais jamais testé de "sélectionner" une case. Sinon on interdit la sélection des cases et c'est bon :)

**Comment by cup2of2tea** [comment]
Je ne sais pas trop d'où pourrait venir le problème (je commence à peine à chercher), mais si tu ajoutes ça : "composant.setForeground(Color.BLACK);" juste avant "if(row%2 ==0)" (ligne 64 de ResultsPanel.java), ça change quelque chose?
Peut-être que mac ne produit pas la même chose pour super.getTableCellRendererComponent(...), dans le cas d'une sélection (mais ça n'explique pas le fait qu'on ne puisse pas désélectionner).

**Comment by maelvalais** [comment]
Bien vu, ça marche un peu mieux, sauf quand c'est des lignes paires : 
![capture d ecran 2015-04-20 a 12 38 18](https://cloud.githubusercontent.com/assets/2195781/7228516/2ce5b0f6-e75a-11e4-9db5-568aaf684f0d.png)

**Comment by cup2of2tea** [comment]
On va interdire la sélection, ça sert vraiment à rien dans notre cas, et pour débugger c'est vraiment la galère si je dois passer mon temps à push des modifications en attendant que quelqu'un avec un mac puisse tester.
La sélection aurait pu servir seulement dans le cas où on veut modifier une valeur (ce qu'on ne veut surtout pas dans notre situation), ou pour copier les valeurs (mais pour quelle raison on voudrait ça? On a déjà un bouton export, à la rigueur c'est au moment de l'export que le traitement doit différer pour enregistrer sous une forme ou non (si on veut du verbeux "machin évalué à truc", ou si on veut du "a True\nb True". 
Je crée une issue pour cette amélioration.
