### ISSUE TITLE
Permettre un export de modèle sous différentes formes

### ISSUE THREAD

**Issue by cup2of2tea** [olzd/touist#76]
Une fenêtre de dialogue devrait s'ouvrir lors de la sauvegarde du fichier, proposant à l'utilisateur une sauvegarde de modèle personnalisée.
Cette fenêtre contiendrait:
- Une liste d'option déroulante dans la partie supérieure du dialogue, permettant de choisir une syntaxe prédéfinie, ou l'option "custom syntax"
- De 5 champs définissant la syntaxe dans la partie inférieure:
 Trois champs textes (utilisés comme séparateur/préfixe/suffixe)
 Deux champs "valeurs" (récupérant les données du modèle) (liste déroulante d'option, permettant de choisir "littéral" ou "valeur")

PREFIXE VALEUR/LITTERAL SEPARATEUR VALEUR/LITTERAL SUFFIXE

**Comment by maelvalais** [comment]
Très bonne idée de permettre à l'utilisateur de pouvoir formater les résultats !
