### ISSUE TITLE
Coloration syntaxique de exact, atleast, atmost, end, diff, when

### ISSUE THREAD

**Issue by maelvalais** [olzd/touist#78]

**Comment by cup2of2tea** [comment]
Quelqu'un connaitrait la syntaxe utilisée pour ces mots (un exemple ou autre...)? J'en aurais besoin pour la conversion latex...
@olzd

**Comment by maelvalais** [comment]
Je viens d'essayer `exact(2,..)` mais je ne sais pas quoi mettre dans `…` :( @olzd saura répondre !

**Comment by cup2of2tea** [comment]
Tu es sûr pour la syntaxe, ou ça pourrait être comme un bigand? (exact 2 $i in A : machin end ? )

**Comment by maelvalais** [comment]
Aucune idée, faut attendre que @olzd se lève ^^

**Comment by olzd** [comment]
J'étais parti sur un truc du genre `exact(2, $i, [1..9], A($i))` vu que la syntaxe n'a jamais été définie...

**Comment by maelvalais** [comment]
Manque `diff()` je crois

**Comment by maelvalais** [comment]
Manque aussi `when`
