### ISSUE TITLE
Le traducteur rend maintenant des variables du type "&1", "&34" qu'il faut supprimer de la fenêtre de résultat

### ISSUE THREAD

**Issue by maelvalais** [olzd/touist#88]
C'est lié aux changements de @olzd dans #86: 
![capture d ecran 2015-05-01 a 21 32 32](https://cloud.githubusercontent.com/assets/2195781/7436028/9b55d82a-f049-11e4-9a8b-eac60ff03ed9.png)

**Comment by cup2of2tea** [comment]
Toutes les variables à éliminer se présentent sous cette forme? "&" suivi d'un nombre?

**Comment by maelvalais** [comment]
Oui

**Comment by olzd** [comment]
Oui c'est ça

**Comment by maelvalais** [comment]
A priori on va laisser comme ça, à moins que @aheba arrive à faire quelque chose directement dans `minisat.jar` (voir #93)
